export const portfolio = {
  hero: {
    heading: "Our",
    headingGradient: "Portfolio",
    subtitle: "Delivering excellence across diverse industries",
    image: {
      src: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1600&q=80",
      alt: "Avante Portfolio",
    },
  },
  gallery: {
    badge: "OUR WORK",
    heading: "Projects that inspire",
    subtitle: "Explore our portfolio of successful installations across diverse industries",
    filters: [
      { label: "Restaurants", children: ["Modern", "Premium"] },
      { label: "Cafes" },
      { label: "Hotels & Resorts" },
      { label: "QSR" },
      { label: "Experiential" },
    ],
    projects: [
      // Restaurants — Modern
      {
        title: "Alusia Bahrain",
        location: "Bahrain",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "At Alusia, Bahrain, a restaurant inspired by Mediterranean, Levantine, and Andalusian cuisine, Avante supplied custom kitchen canopies to support the busy kitchen operations. The ventilation system was designed to effectively remove heat, smoke, and cooking fumes, ensuring a safe, clean, and comfortable working environment. Complementing the restaurant's warm Mediterranean-inspired interiors, the canopy solution combines performance and functionality while supporting an exceptional dining experience. This project showcases Avante's ability to deliver reliable and efficient kitchen ventilation solutions tailored to the hospitality industry.",
        image: { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80", alt: "Alusia Bahrain" },
      },
      {
        title: "Birds Sky View Restaurant",
        location: "Downtown Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Perched above the heart of Downtown Dubai, Birds is a luxury dining and entertainment destination that combines exceptional cuisine, live performances, and panoramic views of the city's iconic skyline. To support the venue's demanding kitchen operations, an advanced Ecology Unit was supplied to effectively treat kitchen exhaust emissions, helping manage grease, smoke, and cooking odors before discharge. The system helps maintain cleaner air quality and efficient performance while integrating seamlessly with the building's infrastructure. This project highlights Avante's expertise in delivering reliable air treatment solutions for premium hospitality venues.",
        image: { src: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80", alt: "Birds Sky View Restaurant" },
      },
      {
        title: "Blue Haven",
        location: "Palm Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Located on the iconic Palm Jumeirah, Blue Haven offers a refined waterfront hospitality experience that blends contemporary elegance with the exclusivity of one of Dubai's most prestigious destinations. To support the facility's operational requirements and maintain high environmental standards, Venturi Cowls and an advanced Ecology Unit were incorporated as part of the kitchen exhaust and air treatment system. The Venturi Cowls improve exhaust performance and protect the system from weather conditions, while the Ecology Unit reduces grease, smoke, and cooking emissions before discharge. Together, these systems help ensure cleaner air, reliable operation, and efficient day-to-day performance. This project demonstrates Avante's expertise in delivering effective ventilation and air treatment solutions for premium hospitality developments across the UAE.",
        image: { src: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80", alt: "Blue Haven" },
      },
      {
        title: "Fenix Restaurant",
        location: "Mumbai, India",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Located within The Oberoi, Mumbai, Fenix is an elegant all-day dining destination celebrated for its sophisticated ambiance, expansive views of the Arabian Sea, and diverse culinary offerings that span global cuisines. Designed to provide a refined yet welcoming dining experience, the restaurant seamlessly blends contemporary luxury with exceptional hospitality. To support the demanding requirements of this premium culinary environment, custom-engineered kitchen canopies were supplied to ensure efficient extraction of heat, smoke, and cooking vapors generated by the restaurant's busy kitchen operations. Designed for optimal performance and reliability, the system contributes to a cleaner, safer, and more comfortable workspace while supporting the seamless service standards associated with The Oberoi brand.",
        image: { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Fenix Restaurant" },
      },
      {
        title: "Lady Bird",
        location: "One Central, Trade Center, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "For Lady Bird at 25 Jump Street, Dubai, Avante delivered custom kitchen canopies tailored to the requirements of the venue's dynamic food and beverage operations. Combining creative dining, handcrafted beverages, and a welcoming social atmosphere, Lady Bird has established itself as a distinctive gathering place within one of Dubai's most exciting lifestyle destinations. The ventilation solution was developed to complement the restaurant's operational needs, ensuring efficient extraction throughout the kitchen while supporting smooth day-to-day service. Designed with performance and reliability in mind, the system contributes to an environment where culinary teams can operate comfortably and efficiently.",
        image: { src: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80", alt: "Lady Bird" },
      },
      {
        title: "The Cherry House",
        location: "Sheikh Zayed Road, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Cherry House brings together a specialty coffee roastery, artisan bakery, espresso bar, and contemporary dining experience under one roof on Sheikh Zayed Road, Dubai. Built around craftsmanship, hospitality, and the journey from bean to cup, the venue features warm interiors, open production spaces, and an immersive atmosphere that celebrates the art of coffee and baking. Complementing the venue's culinary operations, custom-engineered kitchen canopies were supplied to efficiently extract heat, smoke, and cooking vapors generated within the kitchen environment. Designed for reliable performance and seamless integration, the system helps maintain a clean and comfortable workspace while supporting the high operational standards expected of a premium hospitality destination.",
        image: { src: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", alt: "The Cherry House" },
      },
      {
        title: "Yubi by Chef Reif Othman",
        location: "Dubai World Trade Centre, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Located at One Central, Dubai World Trade Centre, YUBI is the latest culinary concept by renowned Chef Reif Othman, celebrated for redefining Japanese dining through creativity, precision, and bold flavors. Inspired by Japanese street culture and contemporary urban energy, YUBI offers an interactive handroll experience where guests can enjoy freshly crafted creations prepared right before their eyes. To support the restaurant's high-performance kitchen operations, custom-engineered kitchen canopies were supplied to ensure the efficient extraction of heat, smoke, and cooking vapors. Designed to deliver reliable performance while maintaining a clean and comfortable working environment, the ventilation solution complements Chef Reif's commitment to culinary excellence and exceptional guest experiences.",
        image: { src: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800&q=80", alt: "Yubi by Chef Reif Othman" },
      },
      {
        title: "Din Tai Fung",
        location: "Dubai Hills Mall, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Located in Dubai Hills Mall, Din Tai Fung is the world-renowned Taiwanese restaurant brand that originated in Taipei and gained international recognition. Renowned for its precision, consistency, and attention to detail, the restaurant offers guests a vibrant atmosphere where culinary craftsmanship takes centre stage. To support the restaurant's high-volume kitchen operations, advanced Ecology Units were supplied to effectively manage grease, smoke, and cooking emissions generated during food preparation. Designed to enhance air quality and support environmentally responsible exhaust management. This project demonstrates expertise in providing innovative air treatment solutions for globally recognized food and beverage brands.",
        image: { src: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80", alt: "Din Tai Fung" },
      },
      {
        title: "Al Beiruti",
        location: "DIFC, Dubai Festival City & Nakheel Mall, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Avante has provided kitchen canopies and Ecology Units for several Al Beiruti locations across Dubai, including DIFC, Dubai Festival City, and Nakheel Mall. Inspired by the rich culinary traditions of Beirut, Al Beiruti is renowned for its authentic Lebanese cuisine, vibrant atmosphere, and contemporary interpretation of Middle Eastern hospitality. The ventilation and air treatment solutions were tailored to accommodate the demands of high-volume food preparation, including grilling, baking, and traditional Lebanese cooking processes. Engineered for efficiency and reliability, the systems contribute to effective extraction and treatment of kitchen emissions while supporting the smooth operation of the restaurant's busy kitchens.",
        image: { src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80", alt: "Al Beiruti" },
      },
      {
        title: "Awani",
        location: "Multiple locations — UAE & KSA",
        category: "Restaurants",
        subcategory: "Modern",
        description:
          "Drawing inspiration from the rich culinary traditions of the Levant, Awani has grown into a well-loved dining brand with locations across the UAE and Saudi Arabia, including Al Bateen, JBR, Meadows, U-Walk Riyadh, and Catch 22 Jeddah. Renowned for its contemporary interpretation of Middle Eastern cuisine, Awani combines authentic flavors, vibrant social dining experiences, and elegant interiors that reflect the warmth of regional hospitality. Across multiple locations, comprehensive kitchen ventilation and air treatment solutions were incorporated to accommodate the diverse operational requirements of the brand. Featuring custom-engineered kitchen canopies and advanced Ecology Units, the systems were designed to efficiently manage heat, smoke, grease, and cooking emissions generated by high-volume kitchen operations. Tailored to suit each venue's unique layout and dining concept, the installations contribute to enhanced kitchen performance, improved air quality, and a comfortable environment for both staff and guests, supporting Awani's continued expansion across the region.",
        image: { src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80", alt: "Awani" },
      },

      // Restaurants — Premium
      {
        title: "MeatCo Restaurant",
        location: "Kuwait & Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80", alt: "MeatCo Restaurant" },
      },
      {
        title: "Cipriani",
        location: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80", alt: "Cipriani" },
      },
      {
        title: "SAN Beach",
        location: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=800&q=80", alt: "SAN Beach" },
      },
      {
        title: "LOREN",
        location: "Palm Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80", alt: "LOREN" },
      },
      {
        title: "Gloria Osteria, Big Mamma",
        location: "The Ritz Carlton, DIFC, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Gloria Osteria, Big Mamma" },
      },
      {
        title: "KAIMANA Beach",
        location: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=800&q=80", alt: "KAIMANA Beach" },
      },
      {
        title: "Baoli Beach Club",
        location: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80", alt: "Baoli Beach Club" },
      },
      {
        title: "Cullinan",
        location: "Marsa Al Arab Hotel, Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80", alt: "Cullinan" },
      },
      {
        title: "Berber Bluewaters",
        location: "Bluewaters Island, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        description: "",
        image: { src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80", alt: "Berber Bluewaters" },
      },
    ],
  },
  stats: {
    items: [
      { value: "250+", label: "Projects Completed" },
      { value: "20+", label: "Years Experience" },
      { value: "10+", label: "Countries Served" },
      { value: "100%", label: "Quality Assurance" },
    ],
  },
};
