export const portfolio = {
  hero: {
    heading: "Our",
    headingGradient: "Portfolio",
    subtitle: "Delivering excellence across diverse industries",
    image: {
      src: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1600&q=80",
      alt: "Avante Portfolio",
    },
  },
  gallery: {
    badge: "OUR WORK",
    heading: "Projects that inspire",
    subtitle: "Explore our portfolio of successful installations across diverse industries",
    filters: [
      { label: "Hotels & Resorts" },
      { label: "Restaurants", children: ["Modern", "Premium"] },
      { label: "Cafes" },
      { label: "QSR" },
      { label: "Experiential" },
    ],
    projects: [
      // Restaurants — Modern
      {
        title: "Alusia",
        location: ["Bahrain"],
        outsideLocation: "Bahrain",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies",
        description:
          "At Alusia, Bahrain, a restaurant inspired by Mediterranean, Levantine, and Andalusian cuisine, Avante supplied custom kitchen canopies to support the busy kitchen operations. The ventilation system was designed to effectively remove heat, smoke, and cooking fumes, ensuring a safe, clean, and comfortable working environment. Complementing the restaurant's warm Mediterranean-inspired interiors, the canopy solution combines performance and functionality while supporting an exceptional dining experience.",
        image: { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80", alt: "Alusia" },
      },
      {
        title: "Birds Sky View",
        location: ["Downtown Dubai, UAE"],
        outsideLocation: "Downtown Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Ecology Unit",
        description:
          "Perched above the heart of Downtown Dubai, Birds is a luxury dining and entertainment destination that combines exceptional cuisine, live performances, and panoramic views of the city's iconic skyline. To support the venue's demanding kitchen operations, an advanced Ecology Unit was supplied to effectively treat kitchen exhaust emissions, helping manage grease, smoke, and cooking odors before discharge. The system helps maintain cleaner air quality and efficient performance while integrating seamlessly with the building's infrastructure.",
        image: { src: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80", alt: "Birds Sky View" },
      },
      {
        title: "Blue Haven",
        location: ["Palm Jumeirah, Dubai, UAE"],
        outsideLocation: "Palm Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Venturi Cowls & Ecology Unit",
        description:
          "Located on the iconic Palm Jumeirah, Blue Haven offers a refined waterfront hospitality experience that blends contemporary elegance with the exclusivity of one of Dubai's most prestigious destinations. To support the facility's operational requirements and maintain high environmental standards, Venturi Cowls and an advanced Ecology Unit were incorporated as part of the kitchen exhaust and air treatment system. The Venturi Cowls improve exhaust performance and protect the system from weather conditions, while the Ecology Unit reduces grease, smoke, and cooking emissions before discharge. Together, these systems help ensure cleaner air, reliable operation, and efficient day-to-day performance.",
        image: { src: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80", alt: "Blue Haven" },
      },
      {
        title: "Fenix",
        location: ["Mumbai, India"],
        outsideLocation: "Mumbai, India",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies",
        description:
          "Located within The Oberoi, Mumbai, Fenix is an elegant all-day dining destination celebrated for its sophisticated ambiance, expansive views of the Arabian Sea, and diverse culinary offerings that span global cuisines. Designed to provide a refined yet welcoming dining experience, the restaurant seamlessly blends contemporary luxury with exceptional hospitality. To support the demanding requirements of this premium culinary environment, custom-engineered kitchen canopies were supplied to ensure efficient extraction of heat, smoke, and cooking vapors generated by the restaurant's busy kitchen operations. Designed for optimal performance and reliability, the system contributes to a cleaner, safer, and more comfortable workspace while supporting the seamless service standards associated with The Oberoi brand.",
        image: { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Fenix" },
      },
      {
        title: "Lady Bird, 25 Jump Street",
        location: ["One Central, 25 Jump Street, Trade Center, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies",
        description:
          "For Lady Bird at 25 Jump Street, Dubai, Avante delivered custom kitchen canopies tailored to the requirements of the venue's dynamic food and beverage operations. Combining creative dining, handcrafted beverages, and a welcoming social atmosphere, Lady Bird has established itself as a distinctive gathering place within one of Dubai's most exciting lifestyle destinations. The ventilation solution was developed to complement the restaurant's operational needs, ensuring efficient extraction throughout the kitchen while supporting smooth day-to-day service. Designed with performance and reliability in mind, the system contributes to an environment where culinary teams can operate comfortably and efficiently.",
        image: { src: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80", alt: "Lady Bird, 25 Jump Street" },
      },
      {
        title: "The Cherry House",
        location: ["Sheikh Zayed Road, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies",
        description:
          "Cherry House brings together a specialty coffee roastery, artisan bakery, espresso bar, and contemporary dining experience under one roof on Sheikh Zayed Road, Dubai. Built around craftsmanship, hospitality, and the journey from bean to cup, the venue features warm interiors, open production spaces, and an immersive atmosphere that celebrates the art of coffee and baking. With roasting, baking, and food preparation taking place within a single integrated environment, custom-engineered kitchen canopies were incorporated to address the diverse ventilation requirements of the venue. Designed for efficient extraction and dependable performance, the system supports the smooth operation of both production and culinary spaces while maintaining a comfortable working atmosphere throughout the facility.",
        image: { src: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", alt: "The Cherry House" },
      },
      {
        title: "Yubi by Chef Reif Othman, 25 Jump Street",
        location: ["Dubai World Trade Centre, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies",
        description:
          "Located at One Central, Dubai World Trade Centre, YUBI is the latest culinary concept by renowned Chef Reif Othman, celebrated for redefining Japanese dining through creativity, precision, and bold flavors. Inspired by Japanese street culture and contemporary urban energy, YUBI offers an interactive handroll experience where guests can enjoy freshly crafted creations prepared right before their eyes. Inspired by the restaurant's interactive handroll concept and fast-paced service style, custom-engineered kitchen canopies were supplied to maintain an efficient kitchen environment. The system delivers reliable extraction performance while supporting the precision and consistency that define Chef Reif Othman's culinary vision.",
        image: { src: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800&q=80", alt: "Yubi by Chef Reif Othman, 25 Jump Street" },
      },
      {
        title: "Din Tai Fung",
        location: ["Dubai Hills Mall, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Ecology Units",
        description:
          "Located in Dubai Hills Mall, Din Tai Fung is the world-renowned Taiwanese restaurant brand that originated in Taipei and gained international recognition. Renowned for its precision, consistency, and attention to detail, the restaurant offers guests a vibrant atmosphere where culinary craftsmanship takes centre stage. To support the restaurant's high-volume kitchen operations, advanced Ecology Units were supplied to effectively manage grease, smoke, and cooking emissions generated during food preparation. Designed to enhance air quality and support environmentally responsible exhaust management. This project demonstrates expertise in providing innovative air treatment solutions for globally recognized food and beverage brands.",
        image: { src: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80", alt: "Din Tai Fung" },
      },
      {
        title: "Al Beiruti",
        location: ["DIFC, Dubai Festival City", "Nakheel Mall, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies & Ecology Units",
        description:
          "Avante has provided kitchen canopies and Ecology Units for several Al Beiruti locations across Dubai, including DIFC, Dubai Festival City, and Nakheel Mall. Inspired by the rich culinary traditions of Beirut, Al Beiruti is renowned for its authentic Lebanese cuisine, vibrant atmosphere, and contemporary interpretation of Middle Eastern hospitality. The ventilation and air treatment solutions were tailored to accommodate the demands of high-volume food preparation, including grilling, baking, and traditional Lebanese cooking processes. Engineered for efficiency and reliability, the systems contribute to effective extraction and treatment of kitchen emissions while supporting the smooth operation of the restaurant's busy kitchens.",
        image: { src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80", alt: "Al Beiruti" },
      },
      {
        title: "Awani",
        location: [
          "Awani U-Walk, Riyadh, KSA",
          "Awani Catch 22, Jeddah, KSA",
          "Awani Cafe - Meadows Souk, Al Thanyah Fourth, Emaar, Dubai",
          "Awani Al Bateen, Abu Dhabi, UAE",
          "Awani Beach, JBR, Dubai, UAE",
        ],
        outsideLocation: "Multiple locations in UAE & KSA",
        category: "Restaurants",
        subcategory: "Modern",
        scope: "Kitchen Canopies & Ecology Units",
        description:
          "Drawing inspiration from the rich culinary traditions of the Levant, Awani has grown into a well-loved dining brand with locations across the UAE and Saudi Arabia, including Al Bateen, JBR, Meadows, U-Walk Riyadh, and Catch 22 Jeddah. Renowned for its contemporary interpretation of Middle Eastern cuisine, Awani combines authentic flavors, vibrant social dining experiences, and elegant interiors that reflect the warmth of regional hospitality. Across multiple locations, comprehensive kitchen ventilation and air treatment solutions were incorporated to accommodate the diverse operational requirements of the brand. Featuring custom-engineered kitchen canopies and advanced Ecology Units, the systems were designed to efficiently manage heat, smoke, grease, and cooking emissions generated by high-volume kitchen operations. Tailored to suit each venue's unique layout and dining concept, the installations contribute to enhanced kitchen performance, improved air quality, and a comfortable environment for both staff and guests, supporting Awani's continued expansion across the region.",
        image: { src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80", alt: "Awani" },
      },

      // Restaurants — Premium
      {
        title: "MeatCo",
        location: ["MeatCo Kuwait Restaurant, Kuwait", "Meat Co SMJ, Dubai, UAE"],
        outsideLocation: "Multiple locations in Kuwait & UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies & Ecology Units",
        description:
          "Renowned for its premium cuts, flame-grilled specialties, and sophisticated dining experience, MeatCo has established itself as a leading steakhouse destination across the Middle East. With locations in Kuwait and Dubai's iconic Souk Madinat Jumeirah, the restaurant combines contemporary elegance with a passion for quality ingredients and expertly crafted cuisine. Given the intensity of steakhouse operations, where open-flame grilling and high-temperature cooking are central to the menu, kitchen canopies and Ecology Units were incorporated to accommodate the demands of daily service. The integrated solution provides effective extraction and air treatment, helping maintain optimal kitchen conditions while supporting the restaurant's commitment to delivering an exceptional dining experience.",
        image: { src: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80", alt: "MeatCo" },
      },
      {
        title: "Cipriani",
        location: ["Jumeirah, Dubai, UAE"],
        outsideLocation: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "A symbol of timeless Italian elegance, Cipriani has earned a global reputation for refined hospitality, impeccable service, and authentic Venetian-inspired cuisine. At its Jumeirah location in Dubai, the brand offers a sophisticated waterfront dining experience where classic recipes, premium ingredients, and understated luxury come together in a distinctly Cipriani setting. Reflecting the standards of a world-renowned hospitality brand, custom kitchen canopies were incorporated as part of the restaurant's kitchen infrastructure to accommodate the demands of its culinary operations. Designed to provide reliable extraction and consistent performance, the system supports the seamless execution of daily service while maintaining the high levels of quality and efficiency expected of the Cipriani name.",
        image: { src: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80", alt: "Cipriani" },
      },
      {
        title: "San Beach",
        location: ["Jumeirah, Dubai, UAE"],
        outsideLocation: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "Set against the backdrop of Dubai's coastline, SAN Beach has established itself as one of the city's most sought-after beachfront destinations, combining Mediterranean-inspired dining, laid-back luxury, and breathtaking sea views. With its elegant design, vibrant atmosphere, and seamless blend of dining and leisure experiences, the venue offers guests a sophisticated escape by the water. Tailored to the demands of a high-energy beachfront hospitality concept, custom kitchen canopies were incorporated to accommodate the diverse culinary activities taking place throughout the venue. Delivering dependable extraction performance and efficient airflow management, the system contributes to smooth kitchen operations while supporting the elevated guest experience that defines SAN Beach.",
        image: { src: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=800&q=80", alt: "San Beach" },
      },
      {
        title: "Loren",
        location: ["Palm Jumeirah, Dubai, UAE"],
        outsideLocation: "Palm Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "Bringing the charm of the Italian Riviera to Palm Jumeirah, Loren offers an elegant dining experience inspired by the coastal flavors, lifestyle, and sophistication of Southern Italy. With its stylish interiors, waterfront setting, and menu rooted in authentic Italian cuisine, the restaurant creates an atmosphere that is both refined and effortlessly welcoming. Crafted to complement the pace and precision of a contemporary Italian kitchen, custom kitchen canopies were integrated as part of the venue's back-of-house infrastructure. The solution delivers reliable extraction performance throughout service, supporting the preparation of Loren's signature dishes while maintaining an efficient and comfortable culinary environment behind the scenes.",
        image: { src: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80", alt: "Loren" },
      },
      {
        title: "Gloria Osteria, Big Mamma",
        location: ["Gate Avenue, The Ritz Carlton, DIFC, Dubai, UAE"],
        outsideLocation: "DIFC, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies with Demand Control System",
        description:
          "Created by the renowned Big Mamma Group, Gloria Osteria brings the spirit of classic Italian trattorias to the heart of DIFC, offering guests an immersive dining experience inspired by the glamour, flavors, and hospitality of Italy. Located within The Ritz-Carlton Dubai International Financial Centre, the restaurant is known for its bold interiors, theatrical presentation, and generous Italian cuisine served in a lively and vibrant atmosphere. Reflecting the scale and energy of a bustling Italian dining destination, custom kitchen canopies integrated with a Demand Control Ventilation System were incorporated as part of the project's kitchen infrastructure. By automatically adapting ventilation levels to real-time cooking activity, the system enhances operational efficiency while maintaining optimal kitchen conditions. The intelligent solution aligns with the venue's commitment to delivering exceptional dining experiences while embracing sustainable and energy-conscious operations.",
        image: { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Gloria Osteria, Big Mamma" },
      },
      {
        title: "Kaimana Beach",
        location: ["Jumeirah, Dubai, UAE"],
        outsideLocation: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "Inspired by the laid-back spirit of tropical island living, Kaimana Beach offers a distinctive beachfront experience where ocean views, vibrant dining, and relaxed luxury come together along Dubai's coastline. Drawing influence from the Polynesian word \"Kaimana,\" meaning the power of the ocean, the venue creates an atmosphere that blends coastal elegance with a welcoming social energy. Designed for a destination where dining and leisure seamlessly intertwine, custom kitchen canopies were incorporated to accommodate the demands of the venue's culinary operations. Delivering dependable extraction performance and efficient airflow management, the system supports a comfortable kitchen environment while enabling the smooth execution of service expected from one of Dubai's sought-after beachfront destinations.",
        image: { src: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=800&q=80", alt: "Kaimana Beach" },
      },
      {
        title: "Baoli Beach Club",
        location: ["Jumeirah, Dubai, UAE"],
        outsideLocation: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "Originating from the French Riviera and renowned for its fusion of fine dining, entertainment, and vibrant nightlife, BAOLI has become an internationally recognized lifestyle destination. Its Dubai beach club brings together Mediterranean-inspired elegance, world-class cuisine, and a dynamic social atmosphere, creating an experience that transitions effortlessly from relaxed beachfront dining to energetic evening entertainment. Reflecting the venue's dual identity as both a premium dining destination and a lively social hotspot, custom kitchen canopies were incorporated to accommodate the demands of continuous culinary service throughout the day and night. Designed for dependable performance and operational efficiency, the system supports the seamless execution of BAOLI's hospitality experience while maintaining optimal conditions within the kitchen environment.",
        image: { src: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80", alt: "Baoli Beach Club" },
      },
      {
        title: "Cullinan",
        location: ["Marsa al Arab Hotel, Jumeirah St, Jumeirah, Dubai, UAE"],
        outsideLocation: "Jumeirah, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Ecology Units",
        description:
          "Overlooking the Arabian Gulf from the prestigious Jumeirah Marsa Al Arab, Cullinan offers a refined dining experience inspired by the world's largest rough diamond, reflecting a philosophy of rarity, craftsmanship, and timeless elegance. Combining premium ingredients, sophisticated interiors, and exceptional service, the restaurant has established itself as one of Dubai's most exclusive culinary destinations. In keeping with the standards of a luxury waterfront venue, advanced Ecology Units were integrated into the kitchen exhaust system to ensure effective treatment of cooking emissions before discharge. Engineered to manage grease, smoke, and odors with exceptional efficiency, the solution supports a cleaner and more environmentally responsible operation while aligning with the elevated hospitality experience that defines Cullinan.",
        image: { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80", alt: "Cullinan" },
      },
      {
        title: "Berber",
        location: ["Blue Waters Residence, Marsa Dubai, Bluewaters Island, Dubai, UAE"],
        outsideLocation: "Bluewaters, Dubai, UAE",
        category: "Restaurants",
        subcategory: "Premium",
        scope: "Kitchen Canopies",
        description:
          "Inspired by the rich culinary traditions of North Africa and the Mediterranean, Berber brings together bold flavors, vibrant hospitality, and contemporary design in a unique waterfront setting on Bluewaters Island. The restaurant's warm atmosphere, open-fire cooking influences, and carefully curated dining experience create a destination that celebrates culture, craftsmanship, and shared moments around food. Drawing from a menu that embraces charcoal grilling and traditional cooking techniques, custom kitchen canopies were incorporated to accommodate the demands of an active culinary environment. Designed for dependable performance and seamless integration, the ventilation solution supports the rhythm of the kitchen while helping maintain the standards expected of a modern dining destination overlooking Dubai's iconic waterfront.",
        image: { src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80", alt: "Berber" },
      },

      // Cafes
      {
        title: "BOHOX",
        location: ["Downtown Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Cafes",
        scope: "Ecology Units",
        description:
          "BOHOX reimagines all-day dining through a blend of Mediterranean flavors, wellness-inspired cuisine, and contemporary bohemian design. Nestled in the heart of Downtown Dubai, the venue has become known for its lush interiors, vibrant atmosphere, and thoughtfully curated menu that celebrates fresh, wholesome ingredients. An advanced Ecology Unit forms an integral part of the restaurant's kitchen exhaust system, helping treat grease, smoke, and cooking odors before air is discharged. The solution enables the venue to maintain high environmental standards while preserving the comfortable and inviting atmosphere that has become synonymous with the BOHOX experience.",
        image: { src: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", alt: "BOHOX" },
      },
      {
        title: "EL&N",
        location: ["Yas Bay Waterfront, Abu Dhabi, UAE"],
        outsideLocation: "Abu Dhabi, UAE",
        category: "Cafes",
        scope: "Kitchen Canopies",
        description:
          "Originally founded in London, EL&N has grown into a globally recognized lifestyle café brand celebrated for its signature floral interiors, vibrant pink aesthetic, and indulgent all-day dining experience. Its Yas Bay Waterfront location in Abu Dhabi continues this vision, offering guests a stylish destination where contemporary cuisine, specialty coffee, and elegant surroundings come together. Custom kitchen canopies were incorporated to complement the café's fast-paced kitchen operations, providing dependable ventilation performance. Carefully integrated into the back-of-house infrastructure, the system supports the efficient preparation of EL&N's diverse menu while maintaining the high standards expected of an internationally acclaimed hospitality brand.",
        image: { src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80", alt: "EL&N" },
      },
      {
        title: "Armani Café",
        location: ["Dubai Mall, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Cafes",
        scope: "Ecology Units",
        description:
          "Overlooking the iconic Dubai Fountain from Dubai Mall, Armani/Caffè embodies the understated elegance and timeless sophistication synonymous with the Armani brand. Combining authentic Italian cuisine with contemporary design and impeccable hospitality, the café offers a refined dining experience where every detail reflects Giorgio Armani's signature philosophy of style and simplicity. Behind this premium dining destination, Ecology Units were integrated to enhance the treatment of kitchen exhaust emissions before discharge, while complementing the seamless, high-quality experience that defines Armani/Caffè.",
        image: { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", alt: "Armani Café" },
      },
      {
        title: "Bateel Café",
        location: ["Reem Mall, Abu Dhabi", "Zaa'beel Palace St, Dubai"],
        outsideLocation: "Multiple locations in UAE",
        category: "Cafes",
        scope: "Kitchen Canopies & Ecology Units",
        description:
          "Renowned for combining Middle Eastern heritage with contemporary dining, Bateel Café offers a refined culinary experience centered around gourmet cuisine, specialty coffee, and the brand's world-famous organic dates. Its locations at Reem Mall, Abu Dhabi, and One Za'abeel, Dubai, reflect the brand's commitment to elegant hospitality, premium ingredients, and thoughtfully designed dining spaces. Across both locations, the kitchen infrastructure was enhanced with Kitchen Canopies and Ecology Units, providing a solution suited to the brand's diverse culinary offerings. Working together as an integrated ventilation solution, the systems provide efficient extraction and effective treatment of kitchen exhaust emissions, supporting a clean, comfortable, and environmentally responsible kitchen environment while maintaining the premium standards associated with the Bateel brand.",
        image: { src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80", alt: "Bateel Café" },
      },
      {
        title: "Paul Café",
        location: [
          "Nakheel Mall, Palm Jumeirah, Dubai, UAE",
          "Reem Mall, Abu Dhabi, UAE",
          "Dalma Mall, Abu Dhabi, UAE",
          "Arabian Ranches Souk, Dubai, UAE",
          "Al Jimi Mall, Al Ain, UAE",
          "Nad Al Sheba Mall, Dubai, UAE",
          "Marina Mall, Abu Dhabi, UAE",
        ],
        outsideLocation: "Multiple locations in UAE",
        category: "Cafes",
        scope: "Kitchen Canopies & Ecology Units",
        description:
          "Founded in France in 1889, PAUL has grown into an internationally celebrated bakery and café brand, renowned for its artisanal breads, French pastries, and classic café cuisine. With multiple locations across the UAE, including Dubai, Abu Dhabi, and Al Ain, the brand continues to deliver an authentic Parisian dining experience defined by timeless elegance, traditional baking, and exceptional hospitality. An integrated kitchen ventilation solution featuring Kitchen Canopies and Ecology Units was implemented to accommodate the varied culinary activities taking place throughout each café. From freshly baked breads and viennoiseries to hot kitchen preparations, the integrated solution was tailored to meet the diverse demands of PAUL's culinary operations, ensuring reliable ventilation and effective exhaust air treatment throughout every stage of service.",
        image: { src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80", alt: "Paul Café" },
      },
      {
        title: "Brunch and Cakes",
        location: ["Marassi Galleria, Bahrain", "The Montgomerie, Emirates Hills, Dubai, UAE"],
        outsideLocation: "Multiple locations in Bahrain & UAE",
        category: "Cafes",
        scope: "Kitchen Canopies",
        description:
          "Originating in Barcelona, Brunch & Cake has become an internationally recognized café brand, celebrated for its wholesome cuisine, beautifully presented dishes, and inviting interiors that embody a relaxed Mediterranean lifestyle. Its locations at Marassi Galleria, Bahrain, and The Montgomerie, Dubai, continue the brand's philosophy of creating memorable all-day dining experiences through fresh ingredients, creative menus, and warm hospitality. Kitchen Canopies were incorporated across both locations to accommodate the lively pace of an all-day café where breakfast, brunch, baking, and à la carte dining operate seamlessly throughout the day. Tailored to the brand's diverse culinary offerings, the ventilation solution integrates effortlessly into the kitchen environment, supporting the smooth preparation of every dish while complementing the welcoming atmosphere.",
        image: { src: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80", alt: "Brunch and Cakes" },
      },
      {
        title: "Angel Cakes",
        location: ["Dubai Creek Harbour, Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Cafes",
        scope: "Ecology Unit",
        description:
          "Founded with the vision of making indulgence healthier, Angel Cakes has redefined the café experience through a menu of refined desserts, artisan pastries, and specialty coffee, all crafted without refined sugar, gluten, or artificial ingredients. At its Dubai Creek Harbour location, the café combines contemporary design with mindful dining, offering guests a bright and elegant space that celebrates wellness without compromising on flavor. The kitchen exhaust system was equipped with an Ecology Unit to efficiently treat cooking and baking emissions, promoting cleaner and more environmentally responsible operation. Carefully selected to complement the café's sustainable philosophy, the solution promotes cleaner air quality and environmentally responsible operations while supporting the smooth day-to-day functioning of this modern bakery concept.",
        image: { src: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80", alt: "Angel Cakes" },
      },
      {
        title: "Bake My Day",
        location: ["Downtown Dubai, UAE"],
        outsideLocation: "Dubai, UAE",
        category: "Cafes",
        scope: "Ecology Unit",
        description:
          "From handcrafted celebration cakes to artisan pastries and specialty coffee, Bake My Day has established itself as a contemporary bakery destination where creativity, quality, and craftsmanship come together. Located in Downtown Dubai, the bakery offers an inviting space dedicated to freshly prepared desserts and memorable culinary experiences. To accommodate the demands of continuous baking and dessert production, an Ecology Unit was integrated into the kitchen exhaust system. Designed to effectively treat kitchen emissions before discharge, the solution promotes cleaner and more sustainable operations while allowing the bakery to focus on delivering freshly crafted creations throughout the day.",
        image: { src: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800&q=80", alt: "Bake My Day" },
      },
      {
        title: "Saddle House",
        location: ["Al Qana, Abu Dhabi, UAE", "Al Jimi Mall, Al Ain, UAE"],
        outsideLocation: "Multiple locations in UAE",
        category: "Cafes",
        scope: "Ecology Units",
        description:
          "Born from Dubai's vibrant café culture, Saddle House has evolved from the iconic Saddle concept into a contemporary dining destination where refined comfort food, specialty coffee, and stylish interiors come together. Its locations at Al Qana, Abu Dhabi, and Al Jimi Mall, Al Ain, reflect the brand's signature blend of modern design, relaxed luxury, and memorable hospitality. To complement the dynamic kitchen operations across both venues, Ecology Units were incorporated into the exhaust air treatment system to effectively manage grease, smoke, and cooking odors before discharge. Carefully integrated into the kitchen infrastructure, the solution enhances air quality while supporting the seamless operation of a brand known for its elevated café and dining experience.",
        image: { src: "https://images.unsplash.com/photo-1535007813616-79dc02ba4021?w=800&q=80", alt: "Saddle House" },
      },
    ],
  },
  stats: {
    items: [
      { value: "250+", label: "Projects Completed" },
      { value: "20+", label: "Years Experience" },
      { value: "10+", label: "Countries Served" },
      { value: "100%", label: "Quality Assurance" },
    ],
  },
};
